### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by huangboju** [lannister-capital/lannister-ios#43]
<img width="1720" alt="Screen Shot 2019-06-14 at 10 26 12 AM" src="https://user-images.githubusercontent.com/14818224/59479262-eaf5fa80-8e8e-11e9-9bfc-dac61c741b2c.png">

**Comment by andresousa** [comment]
Thanks @huangboju! I forgot to comment the run script to generate core data model classes on "Build phases". You can pull from master now and try it again.
Closing this issue. Please reopen it in case I'm wrong.
